apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mosquitto-config
spec:
  storageClassName: mosquitto-config
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    path: "/home/broker/config"
    server: "192.168.182.198"
