apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mosquitto-data
spec:
  storageClassName: mosquitto-data
  capacity:
    storage: 5Gi
  accessModes: 
    - ReadWriteOnce
  nfs:
    path: /home/broker/data
    server: 192.168.182.198
