apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mosquitto-log
spec:
  storageClassName: mosquitto-log
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/broker/log
    server: 192.168.182.198
