apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deployapp
  namespace: default
  selfLink: /apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/deployapp
  uid: 1106583d-84bc-4fde-9197-5833ff354a35
spec:
  maxReplicas: 7
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployapp
  targetCPUUtilizationPercentage: 80
